apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./k8s/*
build:
  local:
    push: false
  artifacts:
    - image: backend
      context: ../backend
      docker:
        dockerfile: Dockerfile
    - image: frontend
      context: ../frontend
      docker:
        dockerfile: Dockerfile
