name: Deploy manifests

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths:
      - "infra/**"

jobs:
  deploy:
    name: Apply manifests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save daeb0d0b-9a15-44bf-a4bc-c65389f8da9b
      - run: kubectl apply -f infra/k8s
